import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import Link from "next/link"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const appNav = (
    <>
      <li>
        <Link href="/">LOGO</Link>
      </li>
      <li>
        <Link href="/dashboard">Dashboard</Link>
      </li>
    </>
  )

  const authNav = (
    <>
    <li>
      <Link href='/sign-up'>Sign Up</Link>
    </li>
    <li>
      <Link href='/sign-in'>Sign In</Link>
    </li>
    <li>
      <button>Sign Out</button>
    </li>
    </>
  )

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="flex flex-wrap">
          <ul className="flex gap-4">{appNav}</ul>
          <ul className="flex gap-4">{authNav}</ul>
        </nav>

        <hr />
        
        {children}
      </body>
    </html>
  )
}
